version: '2'

services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./target/build:/var/www/html
      - ./api:/var/www/html/api
    links:
      - db
    dns:
      - 8.8.8.8

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --init-file /database/init.sql
    volumes:
     - /var/lib/mysql
     - ./database:/database
    environment:
     - MYSQL_ROOT_PASSWORD=toor
     - MYSQL_DATABASE=adsss
