version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./target/build:/var/www/html
      - ./api:/var/www/html/api
    links:
      - db
    depends_on:
      - db
    dns:
      - 8.8.8.8

  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    command: --init-file /database/init.sql
    volumes:
     - ./database:/database
    environment:
     - MYSQL_ROOT_PASSWORD=toor
     - MYSQL_DATABASE=adsss
     - MYSQL_TCP_PORT=3307

  e2e:
    build:
      context: .
      dockerfile: e2e/Dockerfile-e2e
    volumes:
      - .:/opt
    command: /bin/wait-for-it.sh -h db -p 3307 -t 60 -- /bin/wait-for-it.sh -h php -p 80 -- npm run e2e
    links:
      - php
      - db
    depends_on:
      - php
      - db
    dns:
      - 8.8.8.8

